version: '3'
services:
  ## PostgresSQL Docker Compose Config
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  ## PgAdmin Docker Compose Config
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  ## Zookeeper and Kafka Configuration
  zookeeper:
    container_name: zookeeper
    networks:
      - broker-kafka
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Broker-Kafka
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    networks:
      - broker-kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # Zipkin
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring

  # Kafdrop Dashboard
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    networks:
      - broker-kafka
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

  # MS-EUREKA-SERVER
  ms-eureka-server:
    image: "push here your Docker Image"
    container_name: ms-eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin

  # MS-USER
  ms-user:
    container_name: ms-user
    image: "push here your Docker Image"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - postgres
      - zipkin

  # MS-OAUTH
  ms-oauth:
    container_name: ms-oauth
    image: "push here your Docker Image"
    environment:
      - OAUTH_CLIENT_NAME= add here your variable
      - OAUTH_CLIENT_SECRET= add here your variable
      - JWT_SECRET= add here your variable
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin

  # MS-CAR
  ms-car:
    container_name: ms-car
    image: "push here your Docker Image"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - postgres
      - zipkin

  # MS-CUSTOMER
  ms-customer:
    container_name: ms-customer
    image: "push here your Docker Image"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - postgres
      - zipkin

  # MS-RENTAL-ORDER
  ms-rental-order:
    container_name: ms-rental-order
    image: "push here your Docker Image"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
      - broker-kafka
    depends_on:
      - postgres
      - zipkin
      - kafka

  # MS-NOTIFICATION
  ms-notification:
    container_name: ms-notification
    image: "push here your Docker Image"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - broker-kafka
    depends_on:
      - zipkin
      - kafka

  # MS-API-GATEWAY
  ms-api-gateway:
    container_name: ms-api-gateway
    image: "push here your Docker Image"
    ports:
      - "8765:8765"
    environment:
      - JWT_SECRET= add here your variable
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin

## Networks
networks:
  broker-kafka:
    driver: bridge
  postgres:
    driver: bridge
  spring:
    driver: bridge

## Volumes
volumes:
  postgres:
  pgadmin: